version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo Installing Backend dependencies...
      - cd Backend
      - npm install --production

  build:
    commands:
      - echo Backend build completed

artifacts:
  files:
    - '*/'
    - appspec.yml
    - scripts/*/
  discard-paths: no