version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/staffinn-backend
    overwrite: yes
hooks:
  ApplicationStop:
    - location: scripts/stop-backend.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/install-deps.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start-backend.sh
      timeout: 120
      runas: ubuntu
